### ISSUE TITLE
Plugin not working with Checkmk 2.0

### ISSUE THREAD

**Issue by josekampos** [RileyMichael/checkmk-notify-teams#2]
This plugin does not work with version 2.0 of Checkmk. I think it has something to do with the python version, could you please confirm if it can run on python3?

Great job and thanks for sharing.

Best regards

José

**Comment by rileymichael** [comment]
Hey @josekampos -- I've just merged support for CMK 2.0. Please let me know if you have any problems, I only tested it briefly.

**Comment by josekampos** [comment]
Thank you, it's working perfectly!
