### ISSUE TITLE
No Status Color

### ISSUE THREAD

**Issue by ohobby** [RileyMichael/checkmk-notify-teams#3]
In the code i can see that the status should be colored, but in teams it has no color.
Has MS changed something in Teams that it is no longer possible, or is this still a BUG (which can also be seen in the example image).

**Comment by rileymichael** [comment]
Testing the payload out on the message card playground (don't have an actual Teams client installed currently), it looks like the `themeColor` is ignored if it's prefixed with a `#`.. you can try removing that from all of the constants and see if it fixes it.

**Comment by moorereason** [comment]
The colors seem to be working for me.
