### ISSUE TITLE
Include timestamp

### ISSUE THREAD

**Issue by moorereason** [RileyMichael/checkmk-notify-teams#4]
### Feature Request

Include the timestamp in the facts

### Rationale

We've had instances were messages were (for whatever reason) delayed in delivery to teams, which caused confusion.  I've updated the facts to include the timestamp and would prefer to not worry about maintaining a fork of the code.

### Proposed Change

Here's my current addition to the facts:

```python
        {
            "name": "Timestamp:",
            "value": "{LONGDATETIME}".format(**context)
        }
```

**Comment by rileymichael** [comment]
Implemented in https://github.com/RileyMichael/checkmk-notify-teams/commit/7cc31a7e9302b252ac14ff6aed5497b0cba74f95

**Comment by moorereason** [comment]
Sweet!  Installed, and it's working great.  Thanks 👍
